[prompt]
about_user = "My name is Towry, a developer"
response_preference = "Don't explain basic concepts; use perplexity search engine in web search"

[env]
# MODEL = "openrouter/qwen/qwen3-coder:free"
MODEL = "openrouter/z-ai/glm-4.5"
OPENROUTER_API_KEY = "@OPENROUTER_API_KEY@"
PERPLEXITY_API_KEY = "@PERPLEXITY_API_KEY@"
GPTME_COSTS = "true"
TOOL_ALLOWLIST = "subagent,save,append,patch,ipython,shell,computer,read,browser"
GPTME_SUGGEST_LLM = "true"
