[prompt]
# about_user = "I am a curious human programmer."
# response_preference = "Don't explain basic concepts"

[env]
MODEL = "openrouter/qwen/qwen3-coder:free"
OPENROUTER_API_KEY = "@OPENROUTER_API_KEY@"
GPTME_COSTS = true
TOOL_ALLOWLIST = "subagent,save,append,patch,ipython,shell,computer,read,browser"
