[colors.primary]
background = "0x14161b"
foreground = "0xffffff"

[colors.normal]
black = "0x14161b"
red = "0xff5f59"
green = "0x44bc44"
yellow = "0xd0bc00"
blue = "0x2fafff"
magenta = "0xfeacd0"
cyan = "0x00d3d0"
white = "0xffffff"

[colors.bright]
black = "0x1e1e1e"
red = "0xff5f5f"
green = "0x44df44"
yellow = "0xefef00"
blue = "0x338fff"
magenta = "0xff66ff"
cyan = "0x00eff0"
white = "0xffffff"

[[colors.indexed_colors]]
index = 16
color = "0xfec43f"

[[colors.indexed_colors]]
index = 17
color = "0xff9580"
