extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  memory:
    bundled: true
    display_name: Memory
    enabled: true
    name: memory
    timeout: 500
    type: builtin
  tutorial:
    bundled: true
    display_name: Tutorial
    enabled: true
    name: tutorial
    timeout: 500
    type: builtin
  ## MCPs
  context7:
    args:
      - '@upstash/context7-mcp'
    bundled: null
    cmd: bunx
    description: Connects to Context7.com's documentation database to provide up-to-date library and framework documentation with intelligent project ranking and customizable token limits.
    enabled: true
    env_keys: []
    envs: {}
    name: context7
    timeout: 300
    type: stdio
  "@modelcontextprotocol/server-memory":
    args:
      - "@modelcontextprotocol/server-memory"
    bundled: null
    cmd: bunx
    description: Connects to the memory of the current session.
    enabled: true
    env_keys: []
    envs: {}
    name: "@modelcontextprotocol/server-memory"
    timeout: 300
    type: stdio
  "@executeautomation/playwright-mcp-server":
    args:
      - "@executeautomation/playwright-mcp-server"
    bundled: null
    cmd: bunx
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: "@executeautomation/playwright-mcp-server"
    timeout: 300
    type: stdio
  mcp-deepwiki:
    args:
      - mcp-deepwiki@latest
    bundled: null
    cmd: bunx
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: mcp-deepwiki
    timeout: 300
    type: stdio
  "filesystem":
    args:
      - "@modelcontextprotocol/server-filesystem"
      - "/Users/towry/workspace"
    bundled: null
    cmd: bunx
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: "@modelcontextprotocol/server-filesystem"
    timeout: 300
    type: stdio
  "github-mcp-server":
    args:
      - stdio
      - --toolsets
      - all
    bundled: null
    enabled: true
    env_keys: ["GITHUB_PERSONAL_ACCESS_TOKEN"]
    envs: {}
    cmd: github-mcp-server
    name: github-mcp-server
    timeout: 300
    type: stdio
  brave-search:
    args:
      - "@modelcontextprotocol/server-brave-search"
    bundled: null
    cmd: bunx
    description: null
    enabled: true
    env_keys: ["BRAVE_API_KEY"]
    envs: {}
    name: brave-search
    timeout: 300
    type: stdio
GOOSE_MODEL: anthropic/claude-sonnet-4
experiments:
  GOOSE_SMART_APPROVE: true
GOOSE_PLANNER_MODEL: anthropic/claude-opus-4
GOOSE_MODE: auto
GOOSE_PROVIDER: openrouter
