GOOSE_PLANNER_PROVIDER: openrouter
GOOSE_PLANNER_MODEL: qwen/qwen3-235b-a22b-thinking-2507
GOOSE_PROVIDER: openrouter
GOOSE_LEAD_MODEL: qwen/qwen3-235b-a22b-thinking-2507
GOOSE_MODE: auto
GOOSE_PROVIDER__TYPE: OpenRouter
GOOSE_MODEL: qwen/qwen3-coder:free
GOOSE_TOOLSHIM: false
GOOSE_TOOLSHIM_OLLAMA_MODEL: mistral-nemo
## lead-worker
### Switch back to lead after n failure turns
GOOSE_LEAD_FAILURE_THRESHOLD: 1
### Number of initial turns using the lead model before switching to the worker model
GOOSE_LEAD_TURNS: 2
# how many turns to fallback to retry the worker model.
GOOSE_LEAD_FALLBACK_TURNS: 2
## Smart context management
GOOSE_CONTEXT_STRATEGY: summarize
GOOSE_MAX_TURNS: 800
extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  memory:
    bundled: true
    display_name: Memory
    enabled: true
    name: memory
    timeout: 500
    type: builtin
  tutorial:
    bundled: true
    display_name: Tutorial
    enabled: false
    name: tutorial
    timeout: 500
    type: builtin
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: false
    name: computercontroller
    timeout: 600
    type: builtin
  ## MCPs
  context7:
    args:
      - "@upstash/context7-mcp"
    bundled: false
    cmd: bunx
    description: Connects to Context7.com's documentation database to provide up-to-date library and framework documentation with intelligent project ranking and customizable token limits.
    enabled: true
    display_name: Context7
    name: context7
    timeout: 300
    type: stdio
  playwright:
    args:
      - "@playwright/mcp@latest"
    bundled: false
    cmd: bunx
    description: Interact with web pages, take screenshots, generate test code, web scraps the page and execute JavaScript in a real browser environment.
    enabled: false
    name: playwright
    display_name: Playwright
    timeout: 300
    type: stdio
  tidewave:
    cmd: mcp-proxy
    args:
      - "http://localhost:4000/tidewave/mcp"
    bundled: false
    enabled: false
    name: tidewave
    display_name: Tidewave AI
    timeout: 300
    type: stdio
  filesystem:
    args:
      - "@modelcontextprotocol/server-filesystem"
      - "/Users/towry/workspace"
      - "/Users/towry/.dotfiles"
      - "/Users/towry/.config/nvim"
    bundled: false
    cmd: bunx
    description: Access the local filesystem.
    enabled: true
    name: fs
    display_name: FileSystem Tool
    timeout: 400
    type: stdio
  github-mcp-server:
    args: ["stdio", "--toolsets", "all"]
    bundled: false
    enabled: false
    description: Use github api to search code, repo, and issue.
    env_keys: ["GITHUB_PERSONAL_ACCESS_TOKEN"]
    envs:
      GITHUB_PERSONAL_ACCESS_TOKEN: "@GITHUB_PERSONAL_ACCESS_TOKEN@"
    cmd: github-mcp-server
    name: github
    timeout: 300
    type: stdio
  brave-search:
    args:
      - "@modelcontextprotocol/server-brave-search"
    bundled: false
    cmd: bunx
    description: Providing both web and local search capabilities.
    enabled: false
    env_keys: ["BRAVE_API_KEY"]
    envs:
      BRAVE_API_KEY: "@BRAVE_API_KEY@"
    name: brave-search
    display_name: Brave Search
    timeout: 800
    type: stdio
  mastergo:
    args:
      - "--bun"
      - "@mastergo/magic-mcp@0.0.4-beta.10"
      - "--token=@MASTERGO_TOKEN@"
      - "--url=https://mastergo.com"
    bundled: false
    cmd: bunx
    description: MasterGo design collaboration and prototyping tool.
    enabled: false
    name: mastergo
    display_name: MasterGo Magic
    timeout: 800
    type: stdio
