name: Sync Repo to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: keninkujovic/gitlab-sync@2.1.0
        with:
          gitlab_url: ${{ secrets.GITLAB_URL }}
          username: ${{ secrets.USERNAME }}
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
